### ISSUE TITLE
FetchAuthTokenCache returning expired tokens

### ISSUE THREAD

**Issue by larkee** [googleapis/google-auth-library-php#308] opened 2020-09-30 02:34 UTC
I am the owner of the Cloud Spanner PHP client library investigating the following customer issue:

> The customer uses PHP Spanner client lib and they deploy their application on GKE.
> - Workload Identity keeps a token for 59min in the metadata server and retrieves a new one every 60min.
> - PHP Spanner client lib keeps a token for 1500sec (25min). When the token expires, client lib retrieves a new access token from the metadata server.
> - The problem is that PHP Spanner client lib keeps a token for 1500sec even when GKE metadata server refreshes new token and previous token expires.
> - Finally Spanner client lib uses the expired token and error for a while.

I believe this issue is caused by the tokens remaining in the cache after the they expire on the backend because [the cache expiry uses the cache config lifetime](https://github.com/googleapis/google-auth-library-php/blob/master/src/CacheTrait.php#L61). The cache expiry should use the token expiry as hinted at in the following fetchAuthToken [TODO](https://github.com/googleapis/google-auth-library-php/blob/9ccaea6037abff9a99b8a58891b9dc8fe0f0d1b8/src/FetchAuthTokenCache.php#L78):

```
        // TODO: correct caching; update the call to setCachedValue to set the expiry
        // to the value returned with the auth token.
```

Implementing the TODO should resolve this issue.

**Comment by xvzf** [comment] 2020-10-02 06:51
We've seen this as well in production, we now have a sidecar application updating the tokens

**Comment by bshaffer** [comment] 2020-10-03 14:05
We do check expiry [here](https://github.com/googleapis/google-auth-library-php/blob/master/src/FetchAuthTokenCache.php#L88), but only if `expires_at` was present when the token was cached. The metadata tokens have an ["expires_in" field](https://github.com/googleapis/google-auth-library-php/blob/master/src/Credentials/GCECredentials.php#L390), so if the cache can use this as well, would that fix this issue?

```php
// in FetchAuthTokenCache.php
if (empty($auth_token['expires_at']) && isset($auth_token['expires_in'])) {
    $auth_token['expires_at'] = time() + $auth_token['expires_in'];
}
       
```

**Comment by bshaffer** [comment] 2020-10-03 14:07
Alternatively this could be done in [`GCECredentials`](https://github.com/googleapis/google-auth-library-php/blob/master/src/Credentials/GCECredentials.php#L390):

```php
$json['expires_at'] = time() + $json['expires_in'];

// store this so we can retrieve it later
$this->lastReceivedToken = $json;

return $json;
```

**Comment by larkee** [comment] 2020-10-08 00:48
@bshaffer Is there any way I can help with this?

Would adding the `GCECredentials` changes you specified and some tests be a sufficient fix?

**Comment by skuruppu** [comment] 2020-10-14 23:11
@bshaffer is it possible for @larkee or someone else from the Spanner team to help implement a fix? This issue is currently affecting a customer.

**Comment by bshaffer** [comment] 2020-10-16 21:37
@skuruppu @larkee please test with the fix we've merged to master in #314. Pull down the latest version (v1.14.3)[https://github.com/googleapis/google-auth-library-php/releases/tag/v1.14.3] to test this! 

Running `composer update` should suffice.

**Comment by skuruppu** [comment] 2020-10-16 22:55
Thanks a lot for the fix @bshaffer. I've forwarded your instructions so that the customer can try the fix.

**Comment by bshaffer** [comment] 2020-10-19 20:09
@skuruppu I will keep this bug open until the customer has confirmed the fix. Please close it when this happens, or comment back here with any updates. Thank you!

**Comment by skuruppu** [comment] 2020-10-19 22:32
Thanks @bshaffer. I will follow-up to make sure the issue is fixed on their side and comment back here.

**Comment by bshaffer** [comment] 2020-10-20 18:02
@skuruppu change of plan, I have been told the proper process is to close this issue and if the customer still experiences the problem we can reopen it or open a new issue.

**Closed by bshaffer** 2020-10-20 18:02 UTC
Labels: :rotating_light:, priority: p1, type: bug
